using L11P_MoreLINQ.Entities;
using L11P_MoreLINQ.Enums;

namespace L11P_MoreLINQ;

public class DataSource
{
    public IEnumerable<Planet> Planets { get; } = new List<Planet>()
    {
        new Planet(1,  "Проксима б",         "Проксима Центавра", 1.27, PlanetType.GasGiant),
        new Planet(2,  "Ригель Кентавра Аб", "Альфа Центавра A",  1.07, PlanetType.Dwarf),
        new Planet(3,  "Ригель Кентавра Bб", "Альфа Центавра B",  0.96, PlanetType.Terrestrial),
        new Planet(4,  "Зармина",            "Звезда Барнарда",   1.12, PlanetType.GasGiant),
        new Planet(5,  "Ле Верьер",          "Луман 16А",         1.22, PlanetType.Terrestrial),
        new Planet(6,  "Адамс",              "Луман 16Б",         1.18, PlanetType.Terrestrial),
        new Planet(7,  "Эйгир",              "Эпсилон Эридана",   0.88, PlanetType.Dwarf),
        new Planet(8,  "Бергельмир",         "Эпсилон Эридана",   1.05, PlanetType.Terrestrial),
        new Planet(9,  "Фафнир",             "Тау Цети",          1.16, PlanetType.Terrestrial),
        new Planet(10, "Сутр",               "Тау Цети",          1.08, PlanetType.GasGiant),
        new Planet(11, "Валлис",             "Звезда Каптейна",   0.76, PlanetType.Terrestrial),
        new Planet(12, "Аркс",               "Звезда Каптейна",   0.88, PlanetType.Terrestrial),
        new Planet(13, "Жар-птица",          "Глизе 581",         1.5,  PlanetType.Dwarf),
        new Planet(14, "Яванна",             "Глизе 581",         1.3,  PlanetType.Terrestrial),
        new Planet(15, "Минас Моргул",       "Глизе 876",         1.8,  PlanetType.GasGiant),
        new Planet(16, "Мордор",             "Глизе 876",         1.6,  PlanetType.Terrestrial),
        new Planet(17, "Галилео",            "55 Канкри",         2.2,  PlanetType.Terrestrial),
        new Planet(18, "Браге",              "55 Канкри",         1.8,  PlanetType.GasGiant),
        new Planet(19, "Сафар",              "Упсилон Андромеды", 1.4,  PlanetType.GasGiant),
        new Planet(20, "Самх",               "Упсилон Андромеды", 1.2,  PlanetType.Dwarf),
        new Planet(21, "Орфей",              "HD 10180",          1.5,  PlanetType.Terrestrial),
        new Planet(22, "Эвридика",           "HD 10180",          1.2,  PlanetType.GasGiant),
        new Planet(23, "Сид",                "HD 40307",          1.3,  PlanetType.GasGiant),
        new Planet(24, "Дамара",             "HD 40307",          1.1,  PlanetType.Dwarf),
        new Planet(25, "Ариэль",             "HD 69830",          1.2,  PlanetType.Dwarf),
        new Planet(26, "Калибан",            "HD 69830",          1.5,  PlanetType.Terrestrial),
        new Planet(27, "Лита",               "Кеплер-11",         1.6,  PlanetType.Terrestrial),
        new Planet(28, "Таласса",            "Кеплер-11",         1.8,  PlanetType.GasGiant),
        new Planet(29, "Бильбо",             "Кеплер-20",         1.4,  PlanetType.Terrestrial),
        new Planet(30, "Фродо",              "Кеплер-20",         1.2,  PlanetType.Dwarf),
        new Planet(31, "Магратея",           "Кеплер-33",         1.5,  PlanetType.Dwarf),
        new Planet(32, "Златовласка",        "Кеплер-33",         1.3,  PlanetType.GasGiant),
        new Planet(33, "Рубикон",            "Кеплер-62",         1.1,  PlanetType.Dwarf),
        new Planet(34, "Одиссея",            "Кеплер-62",         1.3,  PlanetType.GasGiant),
        new Planet(35, "Криптон",            "Кеплер-186",        1.2,  PlanetType.GasGiant),
        new Planet(36, "Вулкан",             "Кеплер-186",        1.4,  PlanetType.Dwarf),
        new Planet(37, "Саган",              "Кеплер-442",        1.5,  PlanetType.Terrestrial),
        new Planet(38, "Космос",             "Кеплер-442",        1.2,  PlanetType.GasGiant),
        new Planet(39, "Экскалибур",         "Кеплер-90",         1.6,  PlanetType.Terrestrial),
        new Planet(40, "Мерлин",             "Кеплер-90",         1.3,  PlanetType.Dwarf),
        new Planet(41, "Эндор",              "ТРАППИСТ-1",        1.4,  PlanetType.Dwarf),
        new Planet(42, "Татуин",             "ТРАППИСТ-1",        1.5,  PlanetType.GasGiant),
        new Planet(43, "Пандора",            "WASP-47",           1.3,  PlanetType.Dwarf),
        new Planet(44, "Мистерио",           "WASP-47",           1.1,  PlanetType.Terrestrial),
        new Planet(45, "Кваоар",             "K2-138",            1.2,  PlanetType.Terrestrial),
        new Planet(46, "Седна",              "K2-138",            1.4,  PlanetType.GasGiant),
        new Planet(47, "Эарендил",           "TOI-700",           1.5,  PlanetType.GasGiant),
        new Planet(48, "Эльвинг",            "TOI-700",           1.2,  PlanetType.Dwarf),
        new Planet(49, "Антигона",           "HD 219134",         1.1,  PlanetType.Terrestrial),
        new Planet(50, "Исмена",             "HD 219134",         1.3,  PlanetType.GasGiant),
        new Planet(51, "Офелия",             "HD 219542",         1.2,  PlanetType.Dwarf),
        new Planet(52, "Десдемона",          "HD 219542",         1.4,  PlanetType.GasGiant),
        new Planet(53, "Персефона",          "Глизе 876",         1.6,  PlanetType.GasGiant),
        new Planet(54, "Аид",                "Глизе 876",         1.7,  PlanetType.Terrestrial),
        new Planet(55, "Гелиос",             "Глизе 876",         1.8,  PlanetType.Terrestrial),
    };
}
