services:
    webapi:
        image: ninphi/weatherforecast
        ports:
            - 5000:5000
            - 5001:5001
        environment:
            ASPNETCORE_URLS: "http://+:5000;https://+:5001"
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/my-cert.pfx
            ASPNETCORE_Kestrel__Certificates__Default__Password: "12qw!@QW"
        volumes:
            - $USERPROFILE/.aspnet/https:/https:ro
        